Issue 500 missing yaml prefixes
biolink/biolink-model pull request #515
Opened 2020-11-12 20:21 UTC by RichardBruskiewich

Missing prefixes resolved as best  as  feasible

2020-11-12 20:56 UTC, deepakunni3 requested changes

2020-11-12 20:56 UTC, deepakunni3 commented on biolink-model.yaml
> +version: 1.4.1
Still a 1.4.0

2020-11-12 21:01 UTC, deepakunni3 commented
Couple of issues that could be addressed as part of this PR:
- `oboformat` prefix defined but curies have `oboFormat`
- https://github.com/biolink/biolink-model/blob/ca7d1f666cfdbb4941a13748afdc4c69f76e78b0/biolink-model.yaml#L608
  - Prefix here should be NCIT instead of CIT
- `isbn` and `issn` prefix definition missing

2020-11-16 23:30 UTC, RichardBruskiewich commented
> Couple of issues that could be addressed as part of this PR:
> 
>     * `oboformat` prefix defined but curies have `oboFormat`

OK, I'll  fix  this  and  commit the  fix in a few minutes.
> 
>     * https://github.com/biolink/biolink-model/blob/ca7d1f666cfdbb4941a13748afdc4c69f76e78b0/biolink-model.yaml#L608
>       
>       
>       * Prefix here should be NCIT instead of CIT

ditto
> 
>     * `isbn` and `issn` prefix definition missing

Actually, no  they  aren't: they  are  in  the context.jsonld  (I  think, imported  from  prefixcommons.org)

2020-11-16 23:52 UTC, cmungall commented
after this can we switch to a stricter checking mode such that it's
impossible to introduce new curies with undeclared prefixes rather than
relying on manual inspection?

would be good to have a prefix report tsv, or a github page per prefix...

On Mon, Nov 16, 2020 at 3:30 PM Richard Bruskiewich <
notifications@github.com> wrote:

> Couple of issues that could be addressed as part of this PR:
>
> * `oboformat` prefix defined but curies have `oboFormat`
>
> OK, I'll fix this and commit the fix in a few minutes.
>
> * https://github.com/biolink/biolink-model/blob/ca7d1f666cfdbb4941a13748afdc4c69f76e78b0/biolink-model.yaml#L608
>
>
>   * Prefix here should be NCIT instead of CIT
>
> ditto
>
> * `isbn` and `issn` prefix definition missing
>
> Actually, no they aren't: they are in the context.jsonld (I think,
> imported from prefixcommons.org)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/biolink/biolink-model/pull/515#issuecomment-728404202>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAMMON7QZPYQVIDCQU3RI3SQGY2XANCNFSM4TTXZU6Q>
> .
>

2020-11-16 23:59 UTC, deepakunni3 commented
@cmungall I agree. Would be useful to have the reports. I'll make a ticket for that

2020-11-16 23:59 UTC, merged

2020-11-22 21:23 UTC, RichardBruskiewich commented
* `isbn` and `issn` prefix definition missing

I was mistaken for some reason in believing that prefixcommons.org prefixes for these were propagating into the model so I put them in