Reorganize chemical substance
biolink/biolink-model pull request #582
Opened 2020-12-16 19:35 UTC by vdancik

2020-12-17 20:07 UTC, deepakunni3 commented on biolink-model.yaml
> +  is_metabolite:
@vdancik This should be `is metabolite` (without the underscore).

2020-12-17 20:10 UTC, deepakunni3 commented on biolink-model.yaml
> +  is_metabolite:
Also, is this slot supposed to hold a boolean value? i.e. `is_metabolite: true`?

If so, then the range should be `boolean` and the domain should be `chemical substance`

2020-12-17 20:10 UTC, deepakunni3 requested changes
Few notes on the PR

2020-12-19 20:08 UTC, RichardBruskiewich requested changes
Seems like you are transforming  `has active ingredient`  from an integral dedicated slot "property" of a drug, into a predicate of an association with the drug.  It may be helpful to review the applicable use cases to better understand whether this design is desirable (or not).

Note that if we keep this design  decision, then  perhaps  'has  excipient` (refers to the inactive components of a drug) should suffer the same fate?

2020-12-21 17:14 UTC, vdancik commented
I agree that it makes sense to transform "has excipient" from a slot to a predicate and also add "is excipient of" inverse predicate.

2021-01-05 02:54 UTC, cmungall commented
> I agree that it makes sense to transform "has excipient" from a slot to a predicate and also add "is excipient of" inverse predicate.

Agreed

2021-01-14 20:52 UTC, RichardBruskiewich approved these changes

2021-01-14 23:05 UTC, merged